name: build, pack & publish
on:
  push:
    tags:
      - v*
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x

      - name: Restore
        run: dotnet restore src

      - name: Build
        run: dotnet build src --no-restore --configuration Release
      
      - name: Pack
        run: dotnet pack src --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      
      - name: Publish NuGet.org
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
